ログの検証を追加

diff --git a/.github/workflows/build-unsigned-archive.yml b/.github/workflows/build-unsigned-archive.yml
--- a/.github/workflows/build-unsigned-archive.yml
+++ b/.github/workflows/build-unsigned-archive.yml
@@ -10,7 +10,7 @@ jobs:
       MINT_PATH: ${{ github.workspace }}/.mint
       TEAM_ID: ${{ secrets.TEAM_ID }}
       APPLE_ID: ${{ secrets.APPLE_ID }}
-      
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -44,6 +44,23 @@ jobs:
 
       - name: Install Ruby dependencies
         run: bundle install
+
+
+      - name: Verify Environment Variables
+        run: |
+          if [ -z "$TEAM_ID" ]; then
+            echo "Error: TEAM_ID is not set."
+            exit 1
+          else
+            echo "TEAM_ID is set."
+          fi
+
+          if [ -z "$APPLE_ID" ]; then
+            echo "Error: APPLE_ID is not set."
+            exit 1
+          else
+            echo "APPLE_ID is set."
+          fi
 
       - name: Build Release Version (Unsigned) via Makefile
         run: make build-release
